Configuration:

  # for FreeBSD: amd64 arm arm64 i386 powerpc riscv sparc64
  # for Debian/Ubuntu Linux: amd64 arm64 armel armhf i386 mips64el mipsel ppc64el s390x
  # for Alma Linux: amd64 aarch64 ppc64el

  Architecture:
    - amd64

  System:
    - FreeBSD
    - Ubuntu