Options:

  # TODO: not implemented
  delete-obsolete: No

  # do not download+overwrite if the local file already exists
  re-download: No

  # folder where downloaded files are saved
  destination-dir: /mnt/iso

  # create subdirectory in `destination-dir` for every system entry and save its files there
  # see `system` section below
  dir-per-system: Yes

  tools:
    # main download tool
    download: curl -o {destination} --progress-bar {url}
    # alternative:
    # download: curl -o {destination} -z {if-modified-since} {url}
    # download: wget -O {destination} -nc {url}
    # download: fetch -m -i {if-modified-since} -o {destination} {url}

    # torrents download tool
    # note: it should quit after downloading
    torrent: aria2c --listen-port 6881 --dht-entry-point router.bittorrent.com:6881 --dht-listen-port 6882 {torrent}
    # aria2c --listen-port 6881 --dht-entry-point router.bittorrent.com:6881  --dht-listen-port 6882 kubuntu-23.10-desktop-amd64.iso.torrent

    #        -d, --dir=<DIR>               The directory to store the downloaded file.
       # -O, --index-out=<INDEX>=<PATH>
       #        Set file path for file with index=INDEX. You can find the file
       #        index using the --show-files option.  PATH is a relative path to
       #        the path specified in --dir option. You can use this option
       #        multiple times. Using this option, you can specify the output
       #        file names of BitTorrent downloads.
      # index for 1 file is 1

    # alternative:
    # ctorrent ???
    # transmission-cli ???

# for FreeBSD: amd64 arm arm64 i386 powerpc riscv sparc64
# for Debian/Ubuntu Linux: amd64 arm64 armel armhf i386 mips64el mipsel ppc64el s390x
# for Alma Linux: amd64 aarch64 ppc64el
  architecture:
    - amd64

  # which ISOs you need?
  system:
    - FreeBSD
    - FreBSD-Archive
    - Ubuntu
    - Kubuntu
    - Lubuntu
    - Alma
    - Arch
    - Clonezilla
    - Rescuezilla
    - Hirens-PE
    - System-Rescue
    - ShredOS
    - TrueNAS-Core
    - TrueNAS-Scale
    - Kali

