Options:

  # TODO: not implemented
  delete-obsolete: No

  iso-folder: /mnt/iso

# for FreeBSD: amd64 arm arm64 i386 powerpc riscv sparc64
# for Debian/Ubuntu Linux: amd64 arm64 armel armhf i386 mips64el mipsel ppc64el s390x
# for Alma Linux: amd64 aarch64 ppc64el
  architecture:
    - amd64

# which ISOs you need?
  system:
    - FreeBSD
    - FreBSD-Archive
    - Ubuntu
    - Kubuntu
    - Lubuntu
    - Alma
    - Clonezilla
    - Rescuezilla
    - TrueNAS-Core
    - TrueNAS-Scale
    - Kali

